### ISSUE TITLE
TypeError: 'ExtractResult' object is not iterable

### ISSUE THREAD

**Issue by SeekPoint** [eukaryote31/openwebtext#22]
(OpenWebText) root@MZ32-00:/share2/OpenWebText# pipenv run python3 openwebtext/download.py clean_urls.txt  --output_dir /share2/OpenWebText
Total chunks:  212699
Downloading chunk 1
  0%|                                                                                                                          | 0/212699 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "openwebtext/download.py", line 170, in download
    text, meta = scrape(url, memoize)
  File "/share2/OpenWebText/openwebtext/scrapers.py", line 69, in newspaper_scraper
    if should_exclude(url):
  File "/share2/OpenWebText/openwebtext/filter.py", line 112, in should_exclude
    domain = '.'.join([x for x in ext if x])
TypeError: 'ExtractResult' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "openwebtext/download.py", line 307, in <module>
    cdata = list(pool.imap(download, chunk, chunksize=1))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: 'ExtractResult' object is not iterable

**Comment by runbaozha** [comment]
I encountered the same problem, and I solve it in this way:

root@xxxxxxxxx# git diff filter.py
diff --git a/filter.py b/filter.py
index 056fb92..93ddaf8 100644
--- a/filter.py
+++ b/filter.py
-       ext = tldextract.extract(url)
-       domain = '.'.join([x for x in ext if x])
-       basedomain = '.'.join(ext[-2:])
+    ext = tldextract.extract(url)
+    domain = '.'.join([x for x in ext.registered_domain if x])
+    basedomain = '.'.join(ext.registered_domain[-2:])
and
root@cxxxxxxxxxxx# git diff download.py
diff --git a/download.py b/download.py
index 27b50e6..3252ae3 100644
--- a/download.py
+++ b/download.py

@@ -170,7 +170,7 @@ def download(
     text, meta = scrape(url, memoize)
 
     ext = tldextract.extract(url)
-    domain = '.'.join([x for x in ext if x])
+    domain = '.'.join([x for x in ext.registered_domain if x])

**Comment by SeekPoint** [comment]
It works, thank @runbaozha

**Comment by ionutmodo** [comment]
@runbaozha @SeekPoint can you please provide some more details on what you did exactly? I am facing the same problem and I cannot figure out the solution

**Comment by ionutmodo** [comment]
I fixed it, thank you!
